modyfied files to CI pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,36 +27,45 @@ jobs:
           pip install -r requirements.txt
 
   code_quality:
-    name: Code Quality Check
-    runs-on: ubuntu-latest
-    needs: setup
-    steps:
-      - name: Run Pre-commit Hooks
-        run: |
-          source myenv/bin/activate
-          pip install pre-commit
-          pre-commit run --all-files
+  name: Code Quality Check
+  runs-on: ubuntu-latest
+  needs: setup
+  steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: 3.9.13
+    - name: Install dependencies
+      run: |
+        python -m venv myenv
+        source myenv/bin/activate
+        pip install pre-commit
+    - name: Run Pre-commit Hooks
+      run: |
+        source myenv/bin/activate
+        pre-commit run --all-files
 
-  tests:
-    name: Run Tests
-    runs-on: ubuntu-latest
-    needs: setup
-    steps:
-      - name: Run Tests
-        run: |
-          source myenv/bin/activate
-          chmod +x tools/run_tests.sh
-          ./tools/run_tests.sh
-      - name: Store Test Reports
-        if: success() || failure()
-        uses: actions/upload-artifact@v2
-        with:
-          name: junit-report
-          path: reports/junit.xml
-      - name: Store Coverage Report
-        if: success() || failure()
-        uses: actions/upload-artifact@v2
-        with:
-          name: coverage-report
-          path: reports/coverage.xml
-
+# tests:
+#   name: Run Tests
+#    runs-on: ubuntu-latest
+#    needs: setup
+#    steps:
+#      - name: Run Tests
+#        run: |
+#          source myenv/bin/activate
+#          chmod +x tools/run_tests.sh
+#          ./tools/run_tests.sh
+#      - name: Store Test Reports
+#        if: success() || failure()
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: junit-report
+#          path: reports/junit.xml
+#      - name: Store Coverage Report
+#        if: success() || failure()
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: coverage-report
+#          path: reports/coverage.xml
